### ISSUE TITLE
Lack of sports content and 4K resolution, "My list" option error

### ISSUE THREAD

**Issue by zuzia-dev** [Paco8/plugin.video.skyott#1]
Peacock/Skyshowtime add-on version: 0.0.6

Operative systems used: Android

Kodi version used: Kodi 20.1 Nexus 

Subscription: Peacock Premium

Description of the bug:
* A total lack of access to sports content: https://www.peacocktv.com/sports 
* Plugin not accessing 4k resolution, when trying to load any video 4K the maximum resolution allowed on playback is only 1080p on Android device.  
* Option "My list" doesn't work.

Debug log:
```
error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'IndexError'>
Error Contents: list index out of range
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.skyott/default.py", line 7, in <module>
     run()
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.skyott/resources/lib/plugin.py", line 301, in run
     router(params)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.skyott/resources/lib/plugin.py", line 252, in router
     add_videos(addon.getLocalizedString(30102), 'movies', sky.get_my_list())
                                                                                                             ^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.skyott/resources/lib/sky.py", line 351, in get_my_list
     return self.parse_catalog(rails[0][1]['items'])
                               ~~~~~^^^
  IndexError: list index out of range
  -->End of Python script error report<--
```

**Comment by Paco8** [comment]
The sports menu is added in version 0.0.7.
Check if "my list" works in this version.

**Comment by Paco8** [comment]
I think all this problems are now fixed, so I close the issue.
