### ISSUE TITLE
main menu does not load

### ISSUE THREAD

**Issue by vbtony** [Paco8/plugin.video.skyott#49]
This just happened, I used this addon for months without a problem then this
 error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'uri'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.skyott/default.py", line 7, in <module>
                                                       run()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.skyott/resources/lib/plugin.py", line 647, in run
                                                       router(params)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.skyott/resources/lib/plugin.py", line 602, in router
                                                       for item in sky.get_main_menu():
                                                                   ^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.skyott/resources/lib/sky.py", line 802, in get_main_menu
                                                       t = {'id': att['alias'], 'title': att['title'], 'slug': att['uri'].replace('/watch',''), 'icon': icon}
                                                                                                               ~~~^^^^^^^
                                                   KeyError: 'uri'
                                                   -->End of Python script error report<--
Please advise
Tony

**Comment by vbtony** [comment]
Thanks. Coffee on the way
